# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "daily" # Checks for updates daily
    open-pull-requests-limit: 99
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
      ibm-sdk:
        patterns:
          - "github.com/IBM/*"
