# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "daily" # Checks for updates daily
    open-pull-requests-limit: 99
    groups:
      kubernetes-1.34:
        patterns:
          - "k8s.io/*"
      ibm-sdk-1.34:
        patterns:
          - "github.com/IBM/*"
    labels:
      - "release-1.34"
    target-branch: "release-1.34"

  - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "daily" # Checks for updates daily
    open-pull-requests-limit: 99
    groups:
      kubernetes-1.33:
        patterns:
          - "k8s.io/*"
      ibm-sdk-1.33:
        patterns:
          - "github.com/IBM/*"
    labels:
      - "release-1.33"
    target-branch: "release-1.33"

  - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "daily" # Checks for updates daily
    open-pull-requests-limit: 99
    groups:
      kubernetes-1.32:
        patterns:
          - "k8s.io/*"
      ibm-sdk-1.32:
        patterns:
          - "github.com/IBM/*"
    labels:
      - "release-1.32"
    target-branch: "release-1.32"

  - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "daily" # Checks for updates daily
    open-pull-requests-limit: 99
    groups:
      kubernetes-1.31:
        patterns:
          - "k8s.io/*"
      ibm-sdk-1.31:
        patterns:
          - "github.com/IBM/*"
    labels:
      - "release-1.31"
    target-branch: "release-1.31"

  - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "daily" # Checks for updates daily
    open-pull-requests-limit: 99
    groups:
      kubernetes-1.30:
        patterns:
          - "k8s.io/*"
      ibm-sdk-1.30:
        patterns:
          - "github.com/IBM/*"
    labels:
      - "release-1.30"
    target-branch: "release-1.30"

  - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "daily" # Checks for updates daily
    open-pull-requests-limit: 99
    groups:
      kubernetes-1.29:
        patterns:
          - "k8s.io/*"
      ibm-sdk-1.29:
        patterns:
          - "github.com/IBM/*"
    labels:
      - "release-1.29"
    target-branch: "release-1.29"
