# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["release-1.34"]
  pull_request:
    branches: ["release-1.34"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6 # v8 available, but only supports >= v2.1.0
        with:
          args: --disable-all --timeout 5m # disable linting, initialize cache
          version: v1.64.8

      - name: Verify LICENSE file
        run: make oss

      - name: Run go fmt (via golangci-lint)
        run: make fmt

      - name: Run lint (via golangci-lint)
        run: make lint

      - name: Rnn lint-sh (via shellcheck)
        run: make lint-sh

      - name: Rnn go vet
        run: make vet

      - name: Run go test
        run: make test

      - name: Run go build
        run: make commands
